"""fix typo in tablename

Revision ID: 747d0a90ea33
Revises: dc2606ebd466
Create Date: 2021-07-03 14:40:04.832830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747d0a90ea33'
down_revision = 'dc2606ebd466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('puppy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puppy_id'], ['puppies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('puppy_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['puppy_id'], ['puppies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('owners')
    # ### end Alembic commands ###
